name: Build

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Upload GitHub Pages artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist/
